### ISSUE TITLE
Slow down sprint in water

### ISSUE THREAD

**Issue by tacotexmex** [octacian/sprint#2]
The player's sprint should be considerably slowed down or disabled when players walk _on_ or _in_ water.

**Comment by octacian** [comment]
965bda22d4fadb2b0b78b071426193b5db6ed359

I hope to expand this a bit in the future as well so that the slowed sprinting effect is slightly decreased if the player has more "traction," but running at the bottom of the water and touching a solid block below. OFC it should be kept in mind that more advanced features such as this will be more intensive and slower with a less optimal internet connection if used on a server, so they should be used with care. And OFC, these features are and will be completely configurable. Also, the default speeds for sprinting and underwater sprinting need to be tweaked a bit, so in the meantime, you'll probably want to do so yourself if you have not already.
